---
title: "Introduction"
output: rmarkdown::html_vignette
date: "`r format(Sys.time(), '%d %B, %Y')`"
author: Mikkel Meyer Andersen
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Introduction}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(fig.width = 7, cache = FALSE)
```

## Introduction

```{r, message=FALSE}
devtools::load_all(".")
library(igraph)
```

## Prüfer codes

See <http://mathworld.wolfram.com/PrueferCode.html>. 

```{r}
s <- all_prufer_sequences(n = 3)
s_str <- apply(s, 1, paste0, collapse = ", ")

par(mfrow = rev(n2mfrow(nrow(s))))
par(mar = c(0, 0, 5, 0))

gs <- prufer_sequences_as_graphs(s)
for (i in seq_along(gs)) {
  plot(gs[[i]], 
       layout = layout_as_tree, 
       vertex.size = 30, 
       main = paste0("{", s[i], "}"))
}
par(mfrow = c(1, 1))
```

Example from here is `{1, 2, 1, 3, 3, 5}` from <http://mathworld.wolfram.com/PrueferCode.html>:

```{r}
s <- c(1, 2, 1, 3, 3, 5)
A <- prufer_to_adjacency_matrix(s)
g <- graph_from_adjacency_matrix(A)

par(mar = c(0, 0, 5, 0))
plot(g,
     layout = layout_as_tree, 
     vertex.size = 30, 
     main = paste0("{", paste0(s, collapse = ", "), "}"))
```

