// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// prufer_to_adjacency_matrix
Rcpp::IntegerMatrix prufer_to_adjacency_matrix(Rcpp::IntegerVector prufer);
RcppExport SEXP _learndgm_prufer_to_adjacency_matrix(SEXP pruferSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type prufer(pruferSEXP);
    rcpp_result_gen = Rcpp::wrap(prufer_to_adjacency_matrix(prufer));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_learndgm_prufer_to_adjacency_matrix", (DL_FUNC) &_learndgm_prufer_to_adjacency_matrix, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_learndgm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
