# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Prüfer sequence to tree
#' 
#' @export
prufer_to_adjacency_matrix <- function(prufer) {
    .Call('_learndgm_prufer_to_adjacency_matrix', PACKAGE = 'learndgm', prufer)
}

#' Remove duplicate models
#' 
#' @export
rcpp_new_all_tcherries_worker <- function(initial_models, kmin1_subsets_idx, n, n_unused, verbose) {
    .Call('_learndgm_rcpp_new_all_tcherries_worker', PACKAGE = 'learndgm', initial_models, kmin1_subsets_idx, n, n_unused, verbose)
}

cpp_annotate_mi <- function(modellist, d) {
    .Call('_learndgm_cpp_annotate_mi', PACKAGE = 'learndgm', modellist, d)
}

mat_indices_to_vec_index <- function(row, column, n, size_upper_tri) {
    .Call('_learndgm_mat_indices_to_vec_index', PACKAGE = 'learndgm', row, column, n, size_upper_tri)
}

find_model_index <- function(models_haystack, cliques_needle) {
    .Call('_learndgm_find_model_index', PACKAGE = 'learndgm', models_haystack, cliques_needle)
}

