# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Prüfer sequence to tree
#' 
#' @export
prufer_to_adjacency_matrix <- function(prufer) {
    .Call('_learndgm_prufer_to_adjacency_matrix', PACKAGE = 'learndgm', prufer)
}

