# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Prüfer sequence to tree
#' 
#' @export
prufer_to_adjacency_matrix <- function(prufer) {
    .Call('_learndgm_prufer_to_adjacency_matrix', PACKAGE = 'learndgm', prufer)
}

#' Remove duplicate models
#' 
#' @export
rcp__remove_equal_models_worker <- function(adj_mats_upper_tri) {
    .Call('_learndgm_rcp__remove_equal_models_worker', PACKAGE = 'learndgm', adj_mats_upper_tri)
}

#' Remove duplicate models
#' 
#' @export
rcpp_all_tcherries_worker <- function(models, kmin1_subsets_idx, n_unused, verbose) {
    .Call('_learndgm_rcpp_all_tcherries_worker', PACKAGE = 'learndgm', models, kmin1_subsets_idx, n_unused, verbose)
}

